// RUN: linalg-hexagon-opt -pass-pipeline='builtin.module(func.func(conv-tiling\
// RUN: {conv-tile-sizes="1:8"}))' %s | FileCheck %s --check-prefix=HEIGHT
// RUN: linalg-hexagon-opt -pass-pipeline='builtin.module(func.func(conv-tiling\
// RUN: {conv-tile-sizes="3:32"}))' %s | FileCheck %s --check-prefix=OC
// RUN: linalg-hexagon-opt -pass-pipeline='builtin.module(func.func(conv-tiling\
// RUN: {conv-tile-sizes="1:8,3:32"}))' %s | FileCheck %s --check-prefix=MULTI

module {
  func.func @main(%arg0: tensor<1x239x27x128xf16>, %arg1: tensor<64x1x1x128xf16>) -> tensor<1x239x27x64xf16> {
    %0 = tensor.empty() : tensor<1x239x27x64xf16>
    %cst = arith.constant 0.000000e+00 : f16
    %1 = tensor.empty() : tensor<1x30x7x4x8x4x32xf16>
    %pack = linalg.pack %arg0 padding_value(%cst : f16) inner_dims_pos = [1, 2, 3]
            inner_tiles = [8, 4, 32] into %1 :
            tensor<1x239x27x128xf16> -> tensor<1x30x7x4x8x4x32xf16>
    %2 = tensor.empty() : tensor<1x30x7x4x8x2x32x2xf16>
    %pack_0 = linalg.pack %pack inner_dims_pos = [5] inner_tiles = [2] into %2 :
              tensor<1x30x7x4x8x4x32xf16> -> tensor<1x30x7x4x8x2x32x2xf16>
    %3 = builtin.unrealized_conversion_cast %pack_0 : tensor<1x30x7x4x8x2x32x2xf16>
         to tensor<1x239x27x128xf16>
    %padded = tensor.pad %arg1 low[0, 0, 0, 0] high[0, 0, 0, 0] {
    ^bb0(%arg2: index, %arg3: index, %arg4: index, %arg5: index):
      tensor.yield %cst : f16
    } : tensor<64x1x1x128xf16> to tensor<64x1x1x128xf16>
    %c2 = arith.constant 2 : index
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    %c1_1 = arith.constant 1 : index
    %c4 = arith.constant 4 : index
    %c16 = arith.constant 16 : index
    %c2_2 = arith.constant 2 : index
    %from_elements = tensor.from_elements %c2, %c32, %c1, %c1_1, %c4, %c16, %c2_2 : tensor<7xindex>
    %reshape = tensor.reshape %padded(%from_elements) :
               (tensor<64x1x1x128xf16>, tensor<7xindex>) -> tensor<2x32x1x1x4x16x2xf16>
    %4 = tensor.empty() : tensor<2x4x1x1x16x32x2xf16>
    %transposed = linalg.transpose ins(%reshape : tensor<2x32x1x1x4x16x2xf16>)
                  outs(%4 : tensor<2x4x1x1x16x32x2xf16>)
                  permutation = [0, 4, 2, 3, 5, 1, 6]
    %5 = builtin.unrealized_conversion_cast %transposed : tensor<2x4x1x1x16x32x2xf16>
         to tensor<64x1x1x128xf16>
    %6 = tensor.empty() : tensor<1x239x27x64xf16>
    %7 = linalg.conv_2d_nhwc_fhwc
         ins(%3, %5 : tensor<1x239x27x128xf16>, tensor<64x1x1x128xf16>)
         outs(%6 : tensor<1x239x27x64xf16>) -> tensor<1x239x27x64xf16>
    %8 = builtin.unrealized_conversion_cast %7 : tensor<1x239x27x64xf16>
         to tensor<1x30x7x2x8x2x32x2xf16>
    %9 = tensor.empty() : tensor<1x30x7x2x8x4x32xf16>
    %unpack = linalg.unpack %8 inner_dims_pos = [5] inner_tiles = [2] into
              %9 : tensor<1x30x7x2x8x2x32x2xf16> -> tensor<1x30x7x2x8x4x32xf16>
    %10 = tensor.empty() : tensor<1x239x27x64xf16>
    %unpack_3 = linalg.unpack %unpack inner_dims_pos = [1, 2, 3] inner_tiles = [8, 4, 32]
                into %10 : tensor<1x30x7x2x8x4x32xf16> -> tensor<1x239x27x64xf16>
    return %unpack_3 : tensor<1x239x27x64xf16>
  }
}

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.

// Test the output for command 1: Tiling the Height dimension
// HEIGHT-LABEL:   func.func @main(
// HEIGHT-SAME:      %[[ARG0:.*]]: tensor<1x239x27x128xf16>,
// HEIGHT-SAME:      %[[ARG1:.*]]: tensor<64x1x1x128xf16>) -> tensor<1x239x27x64xf16> {

// HEIGHT:           %[[INPUT_TENSOR:.*]] = builtin.unrealized_conversion_cast
// HEIGHT-SAME:      %[[VAL_0:.*]] :
// HEIGHT-SAME:      tensor<1x30x7x4x8x2x32x2xf16> to tensor<1x239x27x128xf16>  

// HEIGHT:           %[[FILTER:.*]] = builtin.unrealized_conversion_cast %[[VAL_1:.*]] :
// HEIGHT-SAME:      tensor<2x4x1x1x16x32x2xf16> to tensor<64x1x1x128xf16>

// HEIGHT:           %[[COMP_RES_TENSOR:.*]] = scf.for %[[IDX_0:.*]] = %c0 to %c232
// HEIGHT-SAME:      step %c8 iter_args(%[[RES_TENSOR:.*]] = %[[EMPTY_TENSOR:.*]]) ->
// HEIGHT-SAME:      (tensor<1x239x27x64xf16>) {

// HEIGHT-NEXT:        %[[INPUT_SLICE:.*]] = tensor.extract_slice
// HEIGHT-SAME:        %[[INPUT_TENSOR]][0, %[[IDX_0]], 0, 0] [1, 8, 27, 128] [1, 1, 1, 1] :
// HEIGHT-SAME:        tensor<1x239x27x128xf16> to tensor<1x8x27x128xf16>

// HEIGHT-NEXT:        %[[RES_SLICE:.*]] = tensor.extract_slice
// HEIGHT-SAME:        %[[RES_TENSOR]][0, %[[IDX_0]], 0, 0] [1, 8, 27, 64] [1, 1, 1, 1] :
// HEIGHT-SAME:        tensor<1x239x27x64xf16> to tensor<1x8x27x64xf16>

// HEIGHT-NEXT:        %[[CONV_RES:.*]] = linalg.conv_2d_nhwc_fhwc
// HEIGHT-SAME:        ins(%[[INPUT_SLICE]], %[[FILTER]] :
// HEIGHT-SAME:        tensor<1x8x27x128xf16>, tensor<64x1x1x128xf16>)
// HEIGHT-SAME:        outs(%[[RES_SLICE]] : tensor<1x8x27x64xf16>) -> tensor<1x8x27x64xf16>

// HEIGHT-NEXT:        %[[INSERT_SLICE:.*]] = tensor.insert_slice %[[CONV_RES]] into
// HEIGHT-SAME:        %[[RES_TENSOR]][0, %[[IDX_0]], 0, 0] [1, 8, 27, 64] [1, 1, 1, 1] :
// HEIGHT-SAME:        tensor<1x8x27x64xf16> into tensor<1x239x27x64xf16>

// HEIGHT-NEXT:        scf.yield %[[INSERT_SLICE]] : tensor<1x239x27x64xf16>
// HEIGHT-NEXT:      }

// HEIGHT-NEXT:      %[[INVERSE_PACK:.*]] = builtin.unrealized_conversion_cast
// HEIGHT-SAME:      %[[COMP_RES_TENSOR]] :
// HEIGHT-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>

// HEIGHT-NEXT:      %[[INVERSE_UNPACK:.*]] = builtin.unrealized_conversion_cast
// HEIGHT-SAME:      %[[INVERSE_PACK]] :
// HEIGHT-SAME:      tensor<1x30x7x2x8x2x32x2xf16> to tensor<1x239x27x64xf16>

// HEIGHT-NEXT:      %[[INPUT_SLICE_PEELED:.*]] = tensor.extract_slice
// HEIGHT-SAME:      %[[INPUT_TENSOR]][0, 232, 0, 0] [1, 7, 27, 128] [1, 1, 1, 1] :
// HEIGHT-SAME:      tensor<1x239x27x128xf16> to tensor<1x7x27x128xf16>

// HEIGHT-NEXT:      %[[RES_SLICE_PEELED:.*]] = tensor.extract_slice
// HEIGHT-SAME:      %[[INVERSE_UNPACK]][0, 232, 0, 0] [1, 7, 27, 64] [1, 1, 1, 1] :
// HEIGHT-SAME:      tensor<1x239x27x64xf16> to tensor<1x7x27x64xf16>

// HEIGHT-NEXT:      %[[CONV_RES_PEELED:.*]] = linalg.conv_2d_nhwc_fhwc
// HEIGHT-SAME:      ins(%[[INPUT_SLICE_PEELED]], %[[FILTER]] :
// HEIGHT-SAME:      tensor<1x7x27x128xf16>, tensor<64x1x1x128xf16>)
// HEIGHT-SAME:      outs(%[[RES_SLICE_PEELED]] : tensor<1x7x27x64xf16>) -> tensor<1x7x27x64xf16>

// HEIGHT-NEXT:      %[[CONV_RES_SLICE_PEELED:.*]] = tensor.insert_slice
// HEIGHT-SAME:      %[[CONV_RES_PEELED]] into
// HEIGHT-SAME:      %[[INVERSE_UNPACK]][0, 232, 0, 0] [1, 7, 27, 64] [1, 1, 1, 1] :
// HEIGHT-SAME:      tensor<1x7x27x64xf16> into tensor<1x239x27x64xf16>

// HEIGHT-NEXT:      %[[PACK:.*]] = builtin.unrealized_conversion_cast
// HEIGHT-SAME:      %[[CONV_RES_SLICE_PEELED]] :
// HEIGHT-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>

// HEIGHT:         }


// Test the output for command 2: Tiling the OC dimension
// OC-LABEL:   func.func @main(
// OC-SAME:      %[[ARG0:.*]]: tensor<1x239x27x128xf16>,
// OC-SAME:      %[[ARG1:.*]]: tensor<64x1x1x128xf16>) -> tensor<1x239x27x64xf16> {
// OC:           %[[INPUT_TENSOR:.*]] = builtin.unrealized_conversion_cast %[[VAL_0:.*]] :
// OC-SAME:      tensor<1x30x7x4x8x2x32x2xf16> to tensor<1x239x27x128xf16>
// OC:           %[[FILTER:.*]] = builtin.unrealized_conversion_cast %[[VAL_1:.*]] :
// OC-SAME:      tensor<2x4x1x1x16x32x2xf16> to tensor<64x1x1x128xf16>

// OC:           %[[COMP_RES_TENSOR:.*]] = scf.for %[[IDX_0:.*]] = %c0 to %c64
// OC-SAME:      step %c32 iter_args(%[[RES_TENSOR:.*]] = %[[EMPTY_TENSOR:.*]]) ->
// OC-SAME:      (tensor<1x239x27x64xf16>) {

// OC-NEXT:        %[[FILTER_SLICE:.*]] = tensor.extract_slice
// OC-SAME:        %[[FILTER]]{{\[}}%[[IDX_0]], 0, 0, 0] [32, 1, 1, 128] [1, 1, 1, 1] :
// OC-SAME:        tensor<64x1x1x128xf16> to tensor<32x1x1x128xf16>

// OC-NEXT:        %[[RES_SLICE:.*]] = tensor.extract_slice
// OC-SAME:        %[[RES_TENSOR]][0, 0, 0, %[[IDX_0]]] [1, 239, 27, 32] [1, 1, 1, 1] :
// OC-SAME:        tensor<1x239x27x64xf16> to tensor<1x239x27x32xf16>

// OC-NEXT:        %[[CONV_RES_SLICE:.*]] = linalg.conv_2d_nhwc_fhwc
// OC-SAME:        ins(%[[INPUT_TENSOR]], %[[FILTER_SLICE]] :
// OC-SAME:        tensor<1x239x27x128xf16>, tensor<32x1x1x128xf16>)
// OC-SAME:        outs(%[[RES_SLICE]] : tensor<1x239x27x32xf16>) -> tensor<1x239x27x32xf16>

// OC-NEXT:        %[[INSERT_SLICE:.*]] = tensor.insert_slice %[[CONV_RES_SLICE]] into
// OC-SAME:        %[[RES_TENSOR]][0, 0, 0, %[[IDX_0]]] [1, 239, 27, 32] [1, 1, 1, 1] :
// OC-SAME:        tensor<1x239x27x32xf16> into tensor<1x239x27x64xf16>

// OC-NEXT:        scf.yield %[[INSERT_SLICE]] : tensor<1x239x27x64xf16>
// OC-NEXT:      }

// OC-NEXT:      %[[INVERSE_PACK:.*]] = builtin.unrealized_conversion_cast
// OC-SAME:      %[[COMP_RES_TENSOR]] :
// OC-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>

// OC-NEXT:      %[[INVERSE_UNPACK:.*]] = builtin.unrealized_conversion_cast
// OC-SAME:      %[[INVERSE_PACK]] :
// OC-SAME:      tensor<1x30x7x2x8x2x32x2xf16> to tensor<1x239x27x64xf16>

// OC-NEXT:      %[[PACK:.*]] = builtin.unrealized_conversion_cast
// OC-SAME:      %[[INVERSE_UNPACK]] :
// OC-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>
// OC:         }



// Test the output for command 3: Multidimensional tiling
// MULTI-LABEL:   func.func @main(
// MULTI-SAME:      %[[ARG0:.*]]: tensor<1x239x27x128xf16>,
// MULTI-SAME:      %[[ARG1:.*]]: tensor<64x1x1x128xf16>) -> tensor<1x239x27x64xf16> {

// MULTI:           %[[INPUT_TENSOR:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[VAL_0:.*]] :
// MULTI-SAME:      tensor<1x30x7x4x8x2x32x2xf16> to tensor<1x239x27x128xf16>

// MULTI:           %[[FILTER:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[VAL_1:.*]] :
// MULTI-SAME:      tensor<2x4x1x1x16x32x2xf16> to tensor<64x1x1x128xf16>

// MULTI:           %[[COMP_RES_TENSOR_DIM1:.*]] = scf.for %[[IDX_0:.*]] = %c0 to %c232
// MULTI-SAME:      step %c8 iter_args(%[[RES_TENSOR:.*]] = %[[EMPTY_TENSOR:.*]]) ->
// MULTI-SAME:      (tensor<1x239x27x64xf16>) {

// MULTI-NEXT:        %[[COMP_RES_TENSOR_DIM2:.*]] = scf.for %[[IDX_1:.*]] = %c0 to %c64
// MULTI-SAME:        step %c32 iter_args(%[[RES_TENSOR_TILED:.*]] = %[[RES_TENSOR]]) ->
// MULTI-SAME:        (tensor<1x239x27x64xf16>) {

// MULTI-NEXT:          %[[INPUT_SLICE:.*]] = tensor.extract_slice %[[INPUT_TENSOR]]
// MULTI-SAME:          [0, %[[IDX_0]], 0, 0] [1, 8, 27, 128] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<1x239x27x128xf16> to tensor<1x8x27x128xf16>

// MULTI-NEXT:          %[[FILTER_SLICE:.*]] = tensor.extract_slice %[[FILTER]]
// MULTI-SAME:          {{\[}}%[[IDX_1]], 0, 0, 0] [32, 1, 1, 128] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<64x1x1x128xf16> to tensor<32x1x1x128xf16>

// MULTI-NEXT:          %[[RES_SLICE:.*]] = tensor.extract_slice %[[RES_TENSOR_TILED]]
// MULTI-SAME:          [0, %[[IDX_0]], 0, %[[IDX_1]]] [1, 8, 27, 32] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<1x239x27x64xf16> to tensor<1x8x27x32xf16>

// MULTI-NEXT:          %[[CONV_RES:.*]] = linalg.conv_2d_nhwc_fhwc
// MULTI-SAME:          ins(%[[INPUT_SLICE]], %[[FILTER_SLICE]] :
// MULTI-SAME:          tensor<1x8x27x128xf16>, tensor<32x1x1x128xf16>)
// MULTI-SAME:          outs(%[[RES_SLICE]] : tensor<1x8x27x32xf16>) -> tensor<1x8x27x32xf16>

// MULTI-NEXT:          %[[CONV_RES_SLICE:.*]] = tensor.insert_slice %[[CONV_RES]] into
// MULTI-SAME:          %[[RES_TENSOR_TILED]]
// MULTI-SAME:          [0, %[[IDX_0]], 0, %[[IDX_1]]] [1, 8, 27, 32] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<1x8x27x32xf16> into tensor<1x239x27x64xf16>

// MULTI-NEXT:          scf.yield %[[CONV_RES_SLICE]] : tensor<1x239x27x64xf16>
// MULTI-NEXT:        }
// MULTI-NEXT:        scf.yield %[[COMP_RES_TENSOR_DIM2]] : tensor<1x239x27x64xf16>
// MULTI-NEXT:      }

// MULTI-NEXT:      %[[INVERSE_PACK_0:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[COMP_RES_TENSOR_DIM1]] :
// MULTI-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>

// MULTI-NEXT:      %[[INVERSE_UNPACK_0:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[INVERSE_PACK_0]] :
// MULTI-SAME:      tensor<1x30x7x2x8x2x32x2xf16> to tensor<1x239x27x64xf16>

// MULTI-NEXT:      %[[COMP_RES_TENSOR_PEELED:.*]] = scf.for %[[IDX_PEELED_0:.*]] = %c0 to %c64
// MULTI-SAME:      step %c32 iter_args(%[[RES_TENSOR_PEELED:.*]] = %[[INVERSE_UNPACK_0]]) ->
// MULTI-SAME:      (tensor<1x239x27x64xf16>) {

// MULTI-NEXT:        %[[INPUT_SLICE_PEELED:.*]] = tensor.extract_slice
// MULTI-SAME:        %[[INPUT_TENSOR]][0, 232, 0, 0] [1, 7, 27, 128] [1, 1, 1, 1] :
// MULTI-SAME:        tensor<1x239x27x128xf16> to tensor<1x7x27x128xf16>

// MULTI-NEXT:        %[[FILTER_SLICE_PEELED:.*]] = tensor.extract_slice %[[FILTER]]
// MULTI-SAME:        {{\[}}%[[IDX_PEELED_0]], 0, 0, 0] [32, 1, 1, 128] [1, 1, 1, 1] :
// MULTI-SAME:        tensor<64x1x1x128xf16> to tensor<32x1x1x128xf16>

// MULTI-NEXT:        %[[RES_SLICE_PEELED:.*]] = tensor.extract_slice
// MULTI-SAME:        %[[RES_TENSOR_PEELED]]
// MULTI-SAME:        [0, 232, 0, %[[IDX_PEELED_0]]] [1, 7, 27, 32] [1, 1, 1, 1] :
// MULTI-SAME:        tensor<1x239x27x64xf16> to tensor<1x7x27x32xf16>

// MULTI-NEXT:        %[[CONV_RES_PEELED:.*]] = linalg.conv_2d_nhwc_fhwc
// MULTI-SAME:        ins(%[[INPUT_SLICE_PEELED]], %[[FILTER_SLICE_PEELED]] :
// MULTI-SAME:        tensor<1x7x27x128xf16>, tensor<32x1x1x128xf16>)
// MULTI-SAME:        outs(%[[RES_SLICE_PEELED]] : tensor<1x7x27x32xf16>)
// MULTI-SAME:        -> tensor<1x7x27x32xf16>

// MULTI-NEXT:        %[[CONV_RES_SLICE_PEELED:.*]] = tensor.insert_slice
// MULTI-SAME:        %[[CONV_RES_PEELED]] into %[[RES_TENSOR_PEELED]]
// MULTI-SAME:        [0, 232, 0, %[[IDX_PEELED_0]]] [1, 7, 27, 32] [1, 1, 1, 1] :
// MULTI-SAME:        tensor<1x7x27x32xf16> into tensor<1x239x27x64xf16>

// MULTI-NEXT:        scf.yield %[[CONV_RES_SLICE_PEELED]] : tensor<1x239x27x64xf16>
// MULTI-NEXT:      }

// MULTI-NEXT:      %[[INVERSE_PACK_1:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[COMP_RES_TENSOR_PEELED]] :
// MULTI-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>

// MULTI-NEXT:      %[[INVERSE_UNPACK_1:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[INVERSE_PACK_1]] :
// MULTI-SAME:      tensor<1x30x7x2x8x2x32x2xf16> to tensor<1x239x27x64xf16>

// MULTI-NEXT:      %[[PACK:.*]] = builtin.unrealized_conversion_cast
// MULTI-SAME:      %[[INVERSE_UNPACK_1]] :
// MULTI-SAME:      tensor<1x239x27x64xf16> to tensor<1x30x7x2x8x2x32x2xf16>

// MULTI:         }

