// RUN: linalg-hexagon-opt -pass-pipeline='builtin.module(func.func(conv-tiling\
// RUN: {conv-tile-sizes="1:8"}),canonicalize)' %s | FileCheck %s --check-prefix=HEIGHT
// RUN: linalg-hexagon-opt -pass-pipeline='builtin.module(func.func(conv-tiling\
// RUN: {conv-tile-sizes="3:32"}),canonicalize)' %s | FileCheck %s --check-prefix=OC
// RUN: linalg-hexagon-opt -pass-pipeline='builtin.module(func.func(conv-tiling\
// RUN: {conv-tile-sizes="1:8,3:32"}),canonicalize)' %s | FileCheck %s --check-prefix=MULTI

module {
  func.func @hmx_pipeline_simple(%arg0: memref<1x16x32x128xf16>,
                                 %arg1: memref<224x1x1x128xf16>,
                                 %arg2: memref<1x16x32x224xf16>) {
    %0 = bufferization.to_tensor %arg0 restrict writable : memref<1x16x32x128xf16> to tensor<1x16x32x128xf16>
    %1 = bufferization.to_tensor %arg1 restrict writable : memref<224x1x1x128xf16> to tensor<224x1x1x128xf16>
    %cst = arith.constant 0.000000e+00 : f16
    %2 = tensor.empty() : tensor<1x16x32x224xf16>
    %cst_0 = arith.constant 0.000000e+00 : f16
    %3 = tensor.empty() : tensor<1x2x8x4x8x4x32xf16>
    %pack = linalg.pack %0 padding_value(%cst_0 : f16) inner_dims_pos = [1, 2, 3] inner_tiles = [8, 4, 32]
            into %3 : tensor<1x16x32x128xf16> -> tensor<1x2x8x4x8x4x32xf16>
    %4 = tensor.empty() : tensor<1x2x8x4x8x2x32x2xf16>
    %pack_1 = linalg.pack %pack inner_dims_pos = [5] inner_tiles = [2] into %4
              : tensor<1x2x8x4x8x4x32xf16> -> tensor<1x2x8x4x8x2x32x2xf16>
    %5 = builtin.unrealized_conversion_cast %pack_1 : tensor<1x2x8x4x8x2x32x2xf16> to tensor<1x16x32x128xf16>
    %padded = tensor.pad %1 low[0, 0, 0, 0] high[0, 0, 0, 0] {
    ^bb0(%arg3: index, %arg4: index, %arg5: index, %arg6: index):
      tensor.yield %cst_0 : f16
    } : tensor<224x1x1x128xf16> to tensor<224x1x1x128xf16>
    %c7 = arith.constant 7 : index
    %c32 = arith.constant 32 : index
    %c1 = arith.constant 1 : index
    %c1_2 = arith.constant 1 : index
    %c4 = arith.constant 4 : index
    %c16 = arith.constant 16 : index
    %c2 = arith.constant 2 : index
    %from_elements = tensor.from_elements %c7, %c32, %c1, %c1_2, %c4, %c16, %c2 : tensor<7xindex>
    %reshape = tensor.reshape %padded(%from_elements) : (tensor<224x1x1x128xf16>, tensor<7xindex>)
               -> tensor<7x32x1x1x4x16x2xf16>
    %6 = tensor.empty() : tensor<7x4x1x1x16x32x2xf16>
    %transposed = linalg.transpose ins(%reshape : tensor<7x32x1x1x4x16x2xf16>) outs(%6 : tensor<7x4x1x1x16x32x2xf16>)
                  permutation = [0, 4, 2, 3, 5, 1, 6]
    %7 = builtin.unrealized_conversion_cast %transposed : tensor<7x4x1x1x16x32x2xf16> to tensor<224x1x1x128xf16>
    %8 = tensor.empty() : tensor<1x16x32x224xf16>
    %9 = linalg.conv_2d_nhwc_fhwc ins(%5, %7 : tensor<1x16x32x128xf16>, tensor<224x1x1x128xf16>)
         outs(%8 : tensor<1x16x32x224xf16>) -> tensor<1x16x32x224xf16>
    %10 = builtin.unrealized_conversion_cast %9 : tensor<1x16x32x224xf16> to tensor<1x2x8x7x8x2x32x2xf16>
    %11 = tensor.empty() : tensor<1x2x8x7x8x4x32xf16>
    %unpack = linalg.unpack %10 inner_dims_pos = [5] inner_tiles = [2] into %11
              : tensor<1x2x8x7x8x2x32x2xf16> -> tensor<1x2x8x7x8x4x32xf16>
    %12 = tensor.empty() : tensor<1x16x32x224xf16>
    %unpack_3 = linalg.unpack %unpack inner_dims_pos = [1, 2, 3] inner_tiles = [8, 4, 32] into %12
                : tensor<1x2x8x7x8x4x32xf16> -> tensor<1x16x32x224xf16>
    bufferization.materialize_in_destination %unpack_3 in restrict writable %arg2 : (tensor<1x16x32x224xf16>, memref<1x16x32x224xf16>) -> ()
    return
  }
}

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.


// Test the output for command 1: tiling the height dimension
// HEIGHT-LABEL: func.func @hmx_pipeline_simple(
// HEIGHT-SAME:   %[[ARG0:.*]]: memref<1x16x32x128xf16>,
// HEIGHT-SAME:   %[[ARG1:.*]]: memref<224x1x1x128xf16>,
// HEIGHT-SAME:   %[[ARG2:.*]]: memref<1x16x32x224xf16>) {
// HEIGHT:            %[[RES:.*]] = scf.for [[IDX_0:.*]] = %c0 to %c16 step %c8
// HEIGHT-SAME:       iter_args([[KERNEL:.*]] = [[EMPTY_TENSOR:.*]]) -> (tensor<1x16x32x224xf16>) {

// HEIGHT-NEXT:       %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice
// HEIGHT-SAME:       %4[0, [[IDX_0]], 0, 0] [1, 8, 32, 128] [1, 1, 1, 1] :
// HEIGHT-SAME:       tensor<1x16x32x128xf16> to tensor<1x8x32x128xf16>

// HEIGHT-NEXT:       %[[EXTRACT_SLICE_1:.*]] = tensor.extract_slice
// HEIGHT-SAME:       [[KERNEL]][0, [[IDX_0]], 0, 0] [1, 8, 32, 224] [1, 1, 1, 1] :
// HEIGHT-SAME:       tensor<1x16x32x224xf16> to tensor<1x8x32x224xf16>

// HEIGHT-NEXT:       %[[CONV_RES:.*]] = linalg.conv_2d_nhwc_fhwc
// HEIGHT-SAME:       ins(%[[EXTRACT_SLICE_0]], %[[FILTER:.*]] : tensor<1x8x32x128xf16>,
// HEIGHT-SAME:       tensor<224x1x1x128xf16>)
// HEIGHT-SAME:       outs(%[[EXTRACT_SLICE_1]] : tensor<1x8x32x224xf16>) -> tensor<1x8x32x224xf16>

// HEIGHT-NEXT:       %[[INSERT_SLICE:.*]] = tensor.insert_slice %[[CONV_RES]] into
// HEIGHT-SAME:       [[KERNEL]][0, [[IDX_0]], 0, 0] [1, 8, 32, 224] [1, 1, 1, 1] :
// HEIGHT-SAME:       tensor<1x8x32x224xf16> into tensor<1x16x32x224xf16>

// HEIGHT-NEXT:       scf.yield %[[INSERT_SLICE]] : tensor<1x16x32x224xf16>
// HEIGHT-NEXT:     }
// HEIGHT:          return
// HEIGHT-NEXT:   }


// Test the output for command 2: Tiling the OC dimension
// OC-LABEL:   func.func @hmx_pipeline_simple(
// OC-SAME:      %[[ARG0:.*]]: memref<1x16x32x128xf16>,
// OC-SAME:      %[[ARG1:.*]]: memref<224x1x1x128xf16>,
// OC-SAME:      %[[ARG2:.*]]: memref<1x16x32x224xf16>) {
// OC:           %[[COMP_RES_TENSOR:.*]] = scf.for %[[IDX_0:.*]] = %c0 to %c224
// OC-SAME:      step %c32 iter_args(%[[RES_TENSOR:.*]] = %[[EMPTY_TENSOR:.*]]) ->
// OC-SAME:      (tensor<1x16x32x224xf16>) {

// OC-NEXT:        %[[FILTER_SLICE:.*]] = tensor.extract_slice
// OC-SAME:        %[[FILTER_TENSOR:.*]]{{\[}}%[[IDX_0]], 0, 0, 0] [32, 1, 1, 128] [1, 1, 1, 1] :
// OC-SAME:        tensor<224x1x1x128xf16> to tensor<32x1x1x128xf16>

// OC-NEXT:        %[[RES_SLICE:.*]] = tensor.extract_slice %[[RES_TENSOR]]
// OC-SAME:        [0, 0, 0, %[[IDX_0]]] [1, 16, 32, 32] [1, 1, 1, 1] :
// OC-SAME:        tensor<1x16x32x224xf16> to tensor<1x16x32x32xf16>

// OC-NEXT:        %[[CONV_RES:.*]] = linalg.conv_2d_nhwc_fhwc
// OC-SAME:        ins(%[[INPUT_TENSOR:.*]], %[[FILTER_SLICE]] :
// OC-SAME:        tensor<1x16x32x128xf16>, tensor<32x1x1x128xf16>)
// OC-SAME:        outs(%[[RES_SLICE]] : tensor<1x16x32x32xf16>) -> tensor<1x16x32x32xf16>

// OC-NEXT:        %[[CONV_RES_SLICE:.*]] = tensor.insert_slice %[[CONV_RES]]
// OC-SAME:        into %[[RES_TENSOR]][0, 0, 0, %[[IDX_0]]] [1, 16, 32, 32] [1, 1, 1, 1] :
// OC-SAME:        tensor<1x16x32x32xf16> into tensor<1x16x32x224xf16>

// OC-NEXT:        scf.yield %[[CONV_RES_SLICE]] : tensor<1x16x32x224xf16>
// OC-NEXT:      }
// OC:           return
// OC-NEXT:    }

// Test the output for command 3: Multidimensional tiling
// MULTI-LABEL:   func.func @hmx_pipeline_simple(
// MULTI-SAME:      %[[ARG0:.*]]: memref<1x16x32x128xf16>,
// MULTI-SAME:      %[[ARG1:.*]]: memref<224x1x1x128xf16>,
// MULTI-SAME:      %[[ARG2:.*]]: memref<1x16x32x224xf16>) {

// MULTI:           %[[COMP_RES_TENSOR:.*]] = scf.for %[[IDX_0:.*]] = %c0 to %c16
// MULTI-SAME:      step %c8 iter_args(%[[RES_TENSOR:.*]] = %[[EMPTY_TENSOR:.*]]) ->
// MULTI-SAME:      (tensor<1x16x32x224xf16>) {

// MULTI-NEXT:        %[[COMP_RES_TENSOR_TILED:.*]] = scf.for %[[IDX_1:.*]] = %c0 to %c224
// MULTI-SAME:        step %c32 iter_args(%[[RES_TENSOR_TILED:.*]] = %[[RES_TENSOR]]) ->
// MULTI-SAME:        (tensor<1x16x32x224xf16>) {

// MULTI-NEXT:          %[[INPUT_SLICE:.*]] = tensor.extract_slice
// MULTI-SAME:          %[[INPUT_TENSOR:.*]][0, %[[IDX_0]], 0, 0] [1, 8, 32, 128] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<1x16x32x128xf16> to tensor<1x8x32x128xf16>

// MULTI-NEXT:          %[[FILTER_SLICE:.*]] = tensor.extract_slice
// MULTI-SAME:          %[[INPUT_TENSOR:.*]]{{\[}}%[[IDX_1]], 0, 0, 0] [32, 1, 1, 128] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<224x1x1x128xf16> to tensor<32x1x1x128xf16>

// MULTI-NEXT:          %[[RES_SLICE:.*]] = tensor.extract_slice %[[RES_TENSOR_TILED]]
// MULTI-SAME:          [0, %[[IDX_0]], 0, %[[IDX_1]]] [1, 8, 32, 32] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<1x16x32x224xf16> to tensor<1x8x32x32xf16>

// MULTI-NEXT:          %[[CONV_RES:.*]] = linalg.conv_2d_nhwc_fhwc
// MULTI-SAME:          ins(%[[INPUT_SLICE]], %[[FILTER_SLICE]] :
// MULTI-SAME:          tensor<1x8x32x128xf16>, tensor<32x1x1x128xf16>)
// MULTI-SAME:          outs(%[[RES_SLICE]] : tensor<1x8x32x32xf16>) -> tensor<1x8x32x32xf16>

// MULTI-NEXT:          %[[CONV_RES_SLICE:.*]] = tensor.insert_slice %[[CONV_RES]] into
// MULTI-SAME:          %[[RES_TENSOR_TILED]]
// MULTI-SAME:          [0, %[[IDX_0]], 0, %[[IDX_1]]] [1, 8, 32, 32] [1, 1, 1, 1] :
// MULTI-SAME:          tensor<1x8x32x32xf16> into tensor<1x16x32x224xf16>

// MULTI-NEXT:          scf.yield %[[CONV_RES_SLICE]] : tensor<1x16x32x224xf16>
// MULTI-NEXT:        }
// MULTI-NEXT:        scf.yield %[[COMP_RES_TENSOR_TILED]] : tensor<1x16x32x224xf16>
// MULTI-NEXT:      }

// MULTI:           return
// MULTI-NEXT:    }