name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/hexagon-mlir-artifacts/Hexagon_SDK/6.4.0.2
            ~/hexagon-mlir-artifacts/Tools
            ~/hexagon-mlir-artifacts/Hexagon_KL/1.0.0/hexkl_addon
          key: hexagon-mlir-artifacts-${{ runner.os }}-v1

      - name: Install Tools and Dependencies if needed
        run: |
          if [ ! -d "/tmp/hexagon-mlir-artifacts/Hexagon_SDK/6.4.0.2" ] || [ ! -d "/tmp/hexagon-mlir-artifacts/Tools" ]; then
            echo "Hexagon SDK or Tools not found in cache. Installing..."
            chmod +x ./ci/setup_tools.sh
            ./ci/setup_tools.sh
          else
            echo "Hexagon SDK and Tools found in cache. Skipping installation."
          fi
          export HEXAGON_SDK_ROOT="/tmp/hexagon-mlir-artifacts/Hexagon_SDK/6.4.0.2"
          export HEXAGON_TOOLS="/tmp/hexagon-mlir-artifacts/Tools"
          export HEXKL_ROOT="/tmp/hexagon-mlir-artifacts/Hexagon_KL/1.0.0/hexkl_addon"
          # Persist environment variables for future steps
          echo "HEXAGON_SDK_ROOT=$HEXAGON_SDK_ROOT" >> $GITHUB_ENV
          echo "HEXAGON_TOOLS=$HEXAGON_TOOLS" >> $GITHUB_ENV
          echo "HEXKL_ROOT=$HEXKL_ROOT" >> $GITHUB_ENV
        shell: bash

      - name: Setup Submodules
        run: |
          chmod +x ./ci/setup_submodules.sh
          ./ci/setup_submodules.sh
        shell: bash
      
      # Read expected LLVM hash from the triton submodule
      - name: Get Expected LLVM Hash
        id: llvmhash
        run: |
          HASH=$(cat triton/cmake/llvm-hash.txt | tr -d '[:space:]')
          echo "hash=$HASH" >> $GITHUB_OUTPUT
      
      # Install ccache to speed up LLVM builds
      - name: Install ccache
        run: |
          sudo apt-get update && sudo apt-get install -y ccache
        
      # Cache LLVM build based on the expected hash
      - name: Cache LLVM Build + Install 
        uses: actions/cache@v4
        with: 
          path: |
            ~/llvm-triton/build
            ~/llvm-triton/llvm-project
          key: llvm-${{ runner.os }}-${{ steps.llvmhash.outputs.hash }}
        
      # Run setup script for LLVM if cache miss
      - name: Setup LLVM for Triton if needed
        run: |
          chmod +x ./ci/setup_llvm.sh
          ./ci/setup_llvm.sh
          export LLVM_PROJECT_BUILD_DIR="/tmp/llvm-triton/build"
          echo "LLVM_PROJECT_BUILD_DIR=$LLVM_PROJECT_BUILD_DIR" >> $GITHUB_ENV
        shell: bash
      
      - name: Verify Environment Variables
        run: |
          echo "Using HEXAGON_SDK_ROOT=$HEXAGON_SDK_ROOT"
          echo "Using HEXAGON_TOOLS=$HEXAGON_TOOLS"
          echo "Using HEXKL_ROOT=$HEXKL_ROOT"
          echo "Using LLVM_PROJECT_BUILD_DIR=$LLVM_PROJECT_BUILD_DIR"
        shell: bash
      
      

      
