name: Qualcomm Preflight Checks
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  qcom-preflight-checks:
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/reusable-qcom-preflight-checks-orchestrator.yml@v2.0.10
    with:
        # ✅ Preflight Checkers
        enable-semgrep-scan: true
        enable-dependency-review: true
        enable-repolinter-check: true
        enable-copyright-license-check: true
        enable-commit-email-check: true
        